version: '3'

services:

  node:
    build:
      context: ./node
      dockerfile: Dockerfile
    image: andjsilva/node:dev
    #entrypoint: dockerize -wait tcp://db:3306 -timeout 50s docker-entrypoint.sh
    container_name: node
    networks:
      - nodenet
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - nodenet

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: andjsilva/nginx:dev
    container_name: nginx
    networks:
      - nodenet
    ports:
      - "8080:80"

networks:
  nodenet:
    driver: bridge
